package postgres

import (
	"slices"
	"strings"

	"github.com/bramaos/brama/internal/schema"
)

// The rows the four queries produce, one type each, holding pg_catalog's answers as
// it phrases them. Nothing is interpreted while it is being scanned: turning an
// attnotnull into a Nullable, or an attgenerated byte into "this column cannot be
// written to", is the part worth testing, and it does not need a database to be
// wrong.
type (
	columnRow struct {
		table    string
		name     string
		dataType string
		declared string
		// notNull is pg_attribute.attnotnull, which is the constraint rather than
		// the permission — the inverse of the Nullable the Schema records.
		notNull bool
		length  int64
		// generated is pg_attribute.attgenerated: one byte, empty for a column the
		// database does not compute.
		generated string
	}

	keyRow struct {
		table string
		name  string
		// primary is pg_index.indisprimary. PostgreSQL names the primary key after
		// the table rather than reserving a name for it, so unlike MySQL there is
		// nothing in the name to recognise and this flag is the only answer.
		primary bool
		column  string
	}

	foreignKeyRow struct {
		table            string
		name             string
		column           string
		referencedTable  string
		referencedColumn string
	}
)

// assemble turns four flat result sets into one Schema.
//
// tables is the authority on what exists: a row describing anything absent from it is
// dropped. pg_catalog answers about views, materialised views and the partitions of a
// partitioned table as readily as base tables, and none of those has rows of its own
// to anonymize and transfer.
func assemble(database string, tables []string, columns []columnRow, keys []keyRow, foreignKeys []foreignKeyRow) schema.Schema {
	names := slices.Clone(tables)
	slices.Sort(names)

	// Built once and indexed by name, so the three loops below can attach to a
	// table in any order. The slice is never appended to after this, which is what
	// makes the pointers into it safe to hold.
	built := make([]schema.Table, len(names))
	byName := make(map[string]*schema.Table, len(names))
	for i, name := range names {
		built[i] = schema.Table{Name: name}
		byName[name] = &built[i]
	}

	for _, row := range columns {
		table, ok := byName[row.table]
		if !ok {
			continue
		}
		table.Columns = append(table.Columns, schema.Column{
			Name:      row.name,
			Type:      strings.ToLower(row.dataType),
			Declared:  row.declared,
			Nullable:  !row.notNull,
			Length:    row.length,
			Generated: generated(row.generated),
		})
	}

	// A key over several columns arrives as one row per column, in key order, so
	// each row after the first extends the key it names rather than starting a new
	// one.
	overExpression := expressionKeys(keys)
	for _, row := range keys {
		table, ok := byName[row.table]
		if !ok {
			continue
		}
		if overExpression[key{row.table, row.name}] {
			continue
		}
		if i := slices.IndexFunc(table.Keys, func(k schema.Key) bool { return k.Name == row.name }); i >= 0 {
			table.Keys[i].Columns = append(table.Keys[i].Columns, row.column)
			continue
		}
		table.Keys = append(table.Keys, schema.Key{
			Name:    row.name,
			Columns: []string{row.column},
			Primary: row.primary,
		})
	}

	for _, row := range foreignKeys {
		table, ok := byName[row.table]
		if !ok {
			continue
		}
		if i := slices.IndexFunc(table.ForeignKeys, func(fk schema.ForeignKey) bool { return fk.Name == row.name }); i >= 0 {
			table.ForeignKeys[i].Columns = append(table.ForeignKeys[i].Columns, row.column)
			table.ForeignKeys[i].References.Columns = append(table.ForeignKeys[i].References.Columns, row.referencedColumn)
			continue
		}
		table.ForeignKeys = append(table.ForeignKeys, schema.ForeignKey{
			Name:    row.name,
			Columns: []string{row.column},
			References: schema.Reference{
				Table:   row.referencedTable,
				Columns: []string{row.referencedColumn},
			},
		})
	}

	for i := range built {
		// Primary key first, then the rest by name. pg_catalog's own order is by
		// the index's oid, which is creation order and therefore whatever history
		// a database happens to have had — a Schema that reordered itself between
		// runs would churn the diff of every brama.yaml it is written into.
		slices.SortStableFunc(built[i].Keys, func(a, b schema.Key) int {
			switch {
			case a.Primary == b.Primary:
				return strings.Compare(a.Name, b.Name)
			case a.Primary:
				return -1
			default:
				return 1
			}
		})
		slices.SortStableFunc(built[i].ForeignKeys, func(a, b schema.ForeignKey) int {
			return strings.Compare(a.Name, b.Name)
		})
	}

	return schema.Schema{Database: database, Tables: built}
}

// key identifies one unique key: its name is only unique within its table.
//
// An index name is unique across a whole PostgreSQL schema, not just its table, so
// the table half is redundant here — it is kept because the alternative is a reader
// having to know that, and because a key is a key on either server.
type key struct {
	table string
	name  string
}

// expressionKeys names the unique indexes that constrain an expression rather than a
// column — UNIQUE (lower(slug), kind) — which PostgreSQL records as a zero where a
// column number would go, so no attribute answers to it.
//
// The whole key is dropped, not the nameless part of it. Keeping the rest would
// record a unique key over (kind) alone, which is a constraint the table does not
// have and a promise the Anonymization engine would then try to keep. A key brama
// cannot describe is better absent than wrong.
func expressionKeys(keys []keyRow) map[key]bool {
	over := map[key]bool{}
	for _, row := range keys {
		if row.column == "" {
			over[key{row.table, row.name}] = true
		}
	}
	return over
}

// generated reports whether pg_attribute.attgenerated marks a column as computed by
// the database.
//
// Two spellings: 's' for the stored generated columns PostgreSQL 12 added, 'v' for
// the virtual ones it added in 18. Matched whole rather than tested for emptiness,
// because attgenerated is a one-byte "char" and an empty one has arrived as a space
// and as a NUL often enough that neither should be read as a third kind of generated
// column — an identity column, which reports empty, is written to like any other.
func generated(attgenerated string) bool {
	switch strings.ToLower(strings.TrimSpace(attgenerated)) {
	case "s", "v":
		return true
	default:
		return false
	}
}
